### PR TITLE
made args validation common

### PR DESCRIPTION
**Pull request by cheops**
Hello,
this is a try to make the validation for sync and async common
let me know if you like the idea of the decorators, if not, or if you have another suggestion let me know.
The validation decorators could als be made more generic `required_arg_type(data, dict)` let me know if that is more what you want.
Greetings

### CODE REVIEW

**Comment by yaleman** [comment]
What *benefit* does this bring? 

There's a significant increase in the raw lines of code and overall package complexity for something that's unlikely to ever change once it's implemented.

I appreciate the want to "make it neater" but I feel like things like this add fragility rather than improving the functionality or maintainability of the codebase:

```
  if "appid" in kwargs:
      appid = kwargs["appid"]
  else:
      appid = args[0]
```

**Comment by cheops** [comment]
Hello,
I just want to try to make the validation common
maybe just a function that is called with arguments to do the validation?
```
    def delete_status_validator(self, date_val: datetime.date, time_val: datetime.time):
        """deletestatus arguments validator"""
        if not isinstance(date_val, datetime.date):
            raise ValueError(
                f"date_val should be of type datetime.date, not {type(date_val)}"
            )
        if time_val and not isinstance(time_val, datetime.time):
            raise ValueError(
                f"time_val should be of time datetime.time, not {type(time_val)}"
            )
        yesterday = datetime.date.today() - datetime.timedelta(1)
        tomorrow = datetime.date.today() + datetime.timedelta(1)
        # you can't delete back past yesterday
        if date_val < yesterday:
            raise ValueError(
                f"date_val can only be yesterday or today, you provided {date_val}"
            )
        # you can't delete forward of today
        if date_val >= tomorrow:
            raise ValueError(
                f"date_val can only be yesterday or today, you provided {date_val}"
            )
```

**Comment by yaleman** [comment]
Ok, let me ponder this for a few days. 😄 Thanks

**Comment by cheops** [comment]
perfect, that is the whole idea. And no hard feelings if you do not like it, it is just a proposal after all.

**Comment by yaleman** [comment]
I've rewritten the existing validation in PR #131 to do all the required validation and it fits all but one use case (the time check in `addstatus` which relies on the class config).

Thanks for your suggestions/encouragement to split functionality out to the base class where possible. Can you please review the changes in the other PR and see if you've got any suggestions?

**Comment by cheops** [comment]
Great work in PR #131 !
This one is no longer relevant.

**Pull request closed without merging**
